#!/usr/bin/ruby

%w[irb/completion irb/ext/save-history rubygems wirble interactive_editor].each do |gem|
  begin
    require gem
  rescue LoadError; end
end

IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"

IRB.conf[:PROMPT_MODE] = :SIMPLE


# Load .railsrc
load File.dirname(__FILE__) + '/.railsrc' if ($0 == 'irb' && ENV['RAILS_ENV']) || ($0 == 'script/rails' && Rails.env)
