[".local/share/nvim/lazy/lazy.nvim"]
  type = "git-repo"
  url = "https://github.com/folke/lazy.nvim.git"
  stripComponents = 1
  clone.args = ["--filter=blob:none"]

{{ if or .codespaces .wsl }}

{{ $ezaVersion := "v0.13.1" }}
[".local/bin/eza"]
  type = "archive-file"
  url = "https://github.com/eza-community/eza/releases/download/{{ $ezaVersion }}/eza_x86_64-unknown-linux-musl.zip"
  path = "eza"

{{ $zellijVersion := "v0.38.2" -}}
[".local/bin/zellij"]
  type = "archive-file"
  url = "https://github.com/zellij-org/zellij/releases/download/{{ $zellijVersion }}/zellij-x86_64-unknown-linux-musl.tar.gz"
  path = "zellij"

[".local/bin/rdm"]
	type = "file"
	url = "https://github.com/BlakeWilliams/remote-development-manager/releases/latest/download/rdm-linux-amd64"
  executable = true

[".config/zplug"]
	type = "git-repo"
	url = "https://github.com/zplug/zplug.git"
{{ end }}

{{ if .codespaces }}
[".config/private.nvim"]
  type = "git-repo"
  url = "https://franciscoj:{{.private_nvim_github_token}}@github.com/franciscoj/private.nvim"

[".zshrc_local"]
  type = "file"
  url = "https://franciscoj:{{.private_zsh_github_token}}@raw.githubusercontent.com/franciscoj/private.zsh/master/{{.codespaces_repo}}/zshrc_local"
{{ end }}
