["~/.local/share/nvim/site/pack/packer/start/packer.nvim"]
  type = "git-repo"
  url = "https://github.com/wbthomason/packer.nvim"

{{ if (.codespaces) }}
[".local/bin/exa"]
  type = "file"
  url = "https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip"
  executable = true
    [".local/bin/exa".filter]
      command = "busybox"
      args = ["unzip", "-", "bin/exa", "-p"]

[".local/bin/rdm"]
	type = "file"
	url = "https://github.com/BlakeWilliams/remote-development-manager/releases/latest/download/rdm-linux-amd64"
  executable = true

[".tmux/plugins/tpm"]
	type = "git-repo"
	url = "https://github.com/tmux-plugins/tpm.git"

[".config/zplug"]
	type = "git-repo"
	url = "https://github.com/zplug/zplug.git"

{{ end }}
