{{ if (.codespaces) }}
[".local/bin/exa"]
  type = "file"
  url = "https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip"
  executable = true
    [".local/bin/exa".filter]
      command = "unzip"
      args = ["bin/exa", "-p"]
{{ end }}
