[".local/share/nvim/lazy/lazy.nvim"]
  type = "git-repo"
  url = "https://github.com/folke/lazy.nvim.git"
  stripComponents = 1
  clone.args = ["--filter=blob:none"]

{{ if or .codespaces .wsl }}

{{ $exaVersion := "v0.10.1" }}
[".local/bin/exa"]
  type = "file"
  url = "https://github.com/ogham/exa/releases/download/{{ $exaVersion }}/exa-linux-x86_64-{{ $exaVersion }}.zip"
  executable = true
  filter.command = "busybox"
  filter.args = ["unzip", "-", "bin/exa", "-p"]

{{ $zellijVersion := "v0.38.1" -}}
[".local/bin/zellij"]
  type = "archive-file"
  url = "https://github.com/zellij-org/zellij/releases/download/{{ $zellijVersion }}/zellij-x86_64-unknown-linux-musl.tar.gz"
  path = "zellij"

[".local/bin/rdm"]
	type = "file"
	url = "https://github.com/BlakeWilliams/remote-development-manager/releases/latest/download/rdm-linux-amd64"
  executable = true

[".config/zplug"]
	type = "git-repo"
	url = "https://github.com/zplug/zplug.git"

{{ end }}

{{ if .codespaces }}
[".config/private.nvim"]
  type = "git-repo"
  url = "https://franciscoj:{{.private_nvim_github_token}}@github.com/franciscoj/private.nvim"
{{ end }}
