" set the vim windows size
set lines=55 columns=170
" Set the macvim font
set guifont=Monaco:h14

if has("gui_macvim")
  " Command-Shift-F for Ack
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<nop>
  map <D-F> :Ack<space>
endif
