" Setup vundler
set rtp+=~/.vim/vundle.git/ 
call vundle#rc()
" Bundles
Bundle "git://github.com/scrooloose/nerdtree.git"
Bundle "git://github.com/mileszs/ack.vim.git"
Bundle "git://github.com/timcharper/textile.vim.git"
Bundle "git://github.com/msanders/snipmate.vim.git"
Bundle "git://github.com/scrooloose/snipmate-snippets.git"
Bundle "git://git.wincent.com/command-t.git"
Bundle "git://github.com/scrooloose/nerdcommenter.git"
Bundle "git://github.com/edsono/vim-matchit.git"
Bundle "git://github.com/tpope/vim-surround.git"
Bundle "git://github.com/tpope/vim-ragtag.git"
Bundle "git://github.com/Raimondi/delimitMate.git"
Bundle "git://github.com/tpope/vim-cucumber.git"

" No need to make it compatible with VI
set nocompatible
" Map the leader character to "," instead of \ (much more easy to use in a
" Spanish keyboard)
let mapleader = ","
" show line numbers
set nu
" Highlight the line with the cursor on it
set cursorline
" Use railscasts colorscheme by Ryan Bates
colorscheme railscasts
" Map toggle the nerdtree with F2
map <F2> :NERDTreeToggle<cr> 
" Map for ack.vim
nnoremap <leader>a :Ack
" Filetype highlighting and indentation activation
syntax on
filetype on
filetype plugin on
filetype indent on
au BufRead,BufNewFile {Capfile,Gemfile,Rakefile,Thorfile,config.ru,.caprc,.irbrc,irb_tempfile*} set ft=ruby
" show available commands for autocomplete in normal mode
set wildmenu
" set the indenting configuration
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
" remove bells and properly ocnfig the status line
set novisualbell  " No blinking .
set noerrorbells  " No noise.
set laststatus=2  " Always show status line.
" Put yanks into clipboard
set clipboard+=unnamed
" Moved the .swp files out of the current dir
set backupdir=~/.vim/tmp/backup,. 
set directory=~/.vim/tmp/swap,.
" Added English spellcheck
set spell
set spelllang=en_us
