import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
]

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_title = true
option_as_alt = "Both"
startup_mode = "Maximized"

# Can't make Control|Shift to work for some reason :shrug:
[keyboard]
bindings = [
{ key = "Space", mods = "Alt|Shift", action = "ToggleViMode" },
]
