# -*- mode: shell-script; -*-

export PATH=$PATH:$HOME/bin

# I want to title my shells by myself.
export DISABLE_AUTO_TITLE=true

# Having PREFIX set makes nvm complaint about it. oh-my-zsh is doing it.
unset PREFIX

# Heroku config
export PATH=/usr/local/heroku/bin:$PATH

# Load direnv
eval "$(direnv hook zsh)"

# Load rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Load rust and cargo
export PATH=$PATH:$HOME/.cargo/bin
export RUST_SRC_PATH=$HOME/Documents/src/rust/src

# Load nvm
export NVM_DIR="$HOME/.nvm"
[[ -s /usr/share/nvm/nvm.sh ]] && . /usr/share/nvm/nvm.sh

# Load local configuration (provided files exist).

# Rubygems allows to split the configuration into different .gemrc equivalent
# files. This .gemrc_local is meant to keep the private configs, like gem
# sources which require username/password.
[[ -f $HOME/.gemrc_local ]] && export GEMRC=$HOME/.gemrc_local

# .zshrc_local is meant to keep private configurations, it is out of version
# management.
[[ -f $HOME/.zprofile_local ]] && source $HOME/.zprofile_local

# Add Yarn global to the path
export PATH="$PATH:`yarn global bin`"
