# -*- mode: shell-script; -*-
export PATH=$PATH:$HOME/bin

# I want to title my shells by myself.
export DISABLE_AUTO_TITLE=true

# Load direnv
eval "$(direnv hook zsh)"

# Load asdf
. $HOME/.asdf/asdf.sh

# Load local configuration (provided files exist).

# Rubygems allows to split the configuration into different .gemrc equivalent
# files. This .gemrc_local is meant to keep the private configs, like gem
# sources which require username/password.
[[ -f $HOME/.gemrc_local ]] && export GEMRC=$HOME/.gemrc_local

# .zshrc_local is meant to keep private configurations, it is out of version
# management.
[[ -f $HOME/.zprofile_local ]] && source $HOME/.zprofile_local
