# -*- mode: shell-script; -*-

dot_files_base=$HOME/Documents/src/dot-files/zsh/
dot_files_platform=`uname`
# Basic PATH so that it can be extended later depending on the platform.
basic_path=$PATH:$HOME/bin

source $dot_files_base/functions.sh

# With this, apps using $EDITOR will use terminal emacs.
export EDITOR='emacsclient -t --alternate-editor="emacs"'
export VISUAL=$EDITOR
# I want to title my shells by myself.
export DISABLE_AUTO_TITLE=true
# Having PREFIX set makes nvm complaint about it. oh-my-zsh is doing it.
unset PREFIX

dot_files_load zshenv

# Load local configuration (provided files exist).

# Rubygems allows to split the configuration into different .gemrc equivalent
# files. This .gemrc_local is meant to keep the private configs, like gem
# sources which require username/password.
[[ -f $HOME/.gemrc_local ]] && export GEMRC=$HOME/.gemrc_local

# .zshrc_local is meant to keep private configurations, it is out of version
# management.
[[ -f $HOME/.zshrc_local ]] && source $HOME/.zshrc_local


# Source the travis CLI if present.
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh
