# -*- mode: shell-script; -*-

dot_files_base=$HOME/Documents/src/dot-files/zsh/
dot_files_platform=`uname`
# Basic PATH so that it can be extended later depending on the platform.
basic_path=$PATH:$HOME/bin

source $dot_files_base/functions.sh

export EDITOR='emacsclient --create-frame --alternate-editor="emacs"'
export VISUAL=$EDITOR

dot_files_load zshenv

# Load local configuration (provided files exist).

# Rubygems allows to split the configuration into different .gemrc equivalent
# files. This .gemrc_local is meant to keep the private configs, like gem
# sources which require username/password.
[[ -f $HOME/.gemrc_local ]] && export GEMRC=$HOME/.gemrc_local

# .zshrc_local is meant to keep private configurations, it is out of version
# management.
[[ -f $HOME/.zshrc_local ]] && source $HOME/.zshrc_local
