# -*- mode: shell-script; -*-
export PATH=$PATH:$HOME/bin:$HOME/.local/bin:$PWD/bin

# Load asdf only if installed
[[ -f $HOME/.asdf/asdf.sh ]] && . $HOME/.asdf/asdf.sh

# Load direnv. Use the full path on mac because :hankey:
# https://github.com/Homebrew/legacy-homebrew/issues/44997#issuecomment-148630030
# Also load local configuration (provided files exist).
case `uname` in
  Darwin)
    eval "$(/usr/local/bin/direnv hook zsh)"
    [[ -f $HOME/.zprofile_local ]] && source $HOME/.zprofile_local
  ;;
  *)
    [[ -x "$(command -v direnv)" ]] && eval "$(direnv hook zsh)"
    [[ -f $HOME/.zshenv_local ]] && source $HOME/.zshenv_local
  ;;
esac

# Rubygems allows to split the configuration into different .gemrc equivalent
# files. This .gemrc_local is meant to keep the private configs, like gem
# sources which require username/password.
[[ -f $HOME/.gemrc_local ]] && export GEMRC=$HOME/.gemrc_local

source "$HOME/.cargo/env"
