export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="sunrise"
plugins=(git github gem rails rbenv heroku common-aliases)
source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/bin:/usr/local/bin/"
export PATH="/usr/local/heroku/bin:$PATH"
export HIPCHAT_USER='Fran Casas'
export EDITOR='emacs -t'
export DISABLE_AUTO_TITLE=true

# Aliases
alias be='bundle exec'
alias rake='bundle exec rake'
alias migrate='rake db:migrate db:test:clone'
alias rspec='bundle exec rspec'
alias r='rspec'
alias p='teamocil --here'
alias e='emacs -nw'

[[ -f $HOME/.gemrc_local ]] && export GEMRC='$HOME/.gemrc_local'
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh
[[ -f $HOME/.zshrc ]] && source $HOME/.zshrc_local
