# Path oh-my-zsh configuration.

export ZSH=$HOME/.oh-my-zsh

export ZSH_THEME="candy"
export DISABLE_AUTO_TITLE=true
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_FIXTERM=false
export ZSH_TMUX_AUTOQUIT=false

plugins=(git gem rails3 tmux bundler rbenv vundle)

source $ZSH/oh-my-zsh.sh

if [[ -z $TMUX ]]; then
  export PATH="$HOME/bin:$HOME/.rbenv/bin:/usr/local/bin:/usr/local/sbin:$PATH"
  eval "$(rbenv init -)"
  ### Added by the Heroku Toolbelt
  export PATH="/usr/local/heroku/bin:$PATH"
fi

export RBENV_ROOT="$HOME/.rbenv"

# Set Vim as the default editor
export EDITOR='vim'

# Load tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator
# Load NVM
[[ -s /home/flamel/.nvm/nvm.sh ]] && . /home/flamel/.nvm/nvm.sh

alias rake="bundle exec rake"
alias migrate="rake db:migrate db:test:clone"
alias git="hub"
alias cu='bundle exec cucumber'
alias tcu='CUCUMBER_FORMAT=pretty bundle exec cucumber'
alias cucumber='bundle exec cucumber'
alias rspec='bundle exec rspec'
