# vim: set ft=sh

export TERM='xterm-256color'
export EDITOR='nvim'
export DIFFPROG='nvim -d'

export VISUAL=$EDITOR

alias _="sudo"
alias be="bundle exec"
alias vi='$EDITOR'
alias e='$EDITOR'
alias g='git'

